### ISSUE TITLE
retrodream can't delete partition of the flashrom

### ISSUE THREAD

**Issue by Arnold101knight** [Cpasjuste/retrodream#11]
i'm using a original psu.
my dreamcast have bad flashrom, when i click on region changer on retrodream i got this error and i always have the date asking/games not booting problem, in past i have successfully writed a dump into the flashrom with retrodream and it fixed all.
i dont know why but i have again the same problem.
now instead it say error, can't delete partition, what i can check to fix this? help me please thanks

**Comment by Arnold101knight** [comment]
fixed

**Comment by Cpasjuste** [comment]
Hi @Arnold101knight, sorry for the late reply. 

Can you explain what was your problem so it may help other users ?

Thanks!

**Comment by akudaikon** [comment]
@Arnold101knight What was the solution to this? I am having the same problem. I can read and backup the flashrom without issue. The backup system.rom looks good, so my flashrom chip is valid. But I cannot write to it, even with the 12v and R512 connection. I always receive the "Region changer error. Cannot delete partition" error.
